/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teslapowerwallvalidate;

import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;

/**
 *
 * @author markvaleri
 */
public class DisplayCSVDataAsTable extends javax.swing.JFrame {

    private FileReader in = null;
    private CSVParser parser = null;
         
    // Create the CSVFormat object with the header mapping
    private CSVFormat csv_format;      
    private DefaultTableModel tesla_data;
    private Object mixed_tesla_data[][];
    
    private int julian_day;   
    private String day_of_week;
    private String file_name;
    
    
    /**
     * Creates new form FileDisplayData
     */
    public DisplayCSVDataAsTable() {
        julian_day = 0;
        day_of_week = "Sunday";
        file_name = "Not Opened";
        
        tesla_data = null;
        csv_format = CSVFormat.EXCEL.withHeader();
        initComponents();
        initUserDefinedComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        csv_table = new javax.swing.JTable();
        hide_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        csv_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(csv_table);

        hide_btn.setBackground(new java.awt.Color(51, 255, 51));
        hide_btn.setText("Hide");
        hide_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hide_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hide_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hide_btn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initUserDefinedComponents() {

    }   
    
    private void hide_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hide_btnActionPerformed
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_hide_btnActionPerformed

    public void readCSVFile() {
         
        try {
            // Create a new list of student to be filled by CSV file data 
            List td = new ArrayList();
             
            // initialize FileReader object
            in = new FileReader(file_name);
             
            // initialize CSVParser object
            parser = new CSVParser(in, csv_format);
             
            // Get a list of CSV file records
            // The tesla app csv fike are very smallso we can use the 
            // the .records() method to read the whole file
            // The tesla five this organized in the following format
            // 5 columns date & time, Home data kW, Solar data kW, battery kW, Grid kW
            // each row increnebts time by 5 minutes
            // the numbers of rows is header row plus data rows 60 min / 5 min  * 24 hrs
            //  1 + 288  = 289 rows 
            
            List<CSVRecord> records = parser.getRecords();
     
            int row = 0;
                      
            for (CSVRecord record : records) {
                for (int col = 0; col < record.size(); col++) {
                    String date_time = record.get(col);
                    DateTimeFormatter tf = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'");
                    LocalDateTime date = LocalDateTime.parse(date_time, tf);
     
                    if (row == 0) {
                        julian_day = date.getDayOfYear();
                        day_of_week = date.getDayOfWeek().toString();
                    }

                    if (col == 0) {
                       String time = date.toLocalTime().toString();
                       mixed_tesla_data[row][col] = time;
                       tesla_data.setValueAt(time, row, col);
                    } else {
                        double pwr_usage = Double.parseDouble(record.get(col));
                        mixed_tesla_data[row][col] = pwr_usage;
                        tesla_data.setValueAt(pwr_usage,row, col);
                    }                   
                }
                row++;
            }
            
        } catch (IOException e) {
            System.out.println("Error in CsvFileReader !!!");
//            e.printStackTrace();
        } finally {
            try {
                in.close();
                parser.close();
            } catch (IOException e) {
                System.out.println("Error while closing fileReader/csvFileParser !!!");
//                e.printStackTrace();
            }
        }
    }

    public int getJulianDay() {
        return julian_day;
    }
    
    public String getDayOfWeek() {
        return day_of_week;
    }
    
    public void setFileName(String fn) {
        file_name = fn;
    }
    
    public String getFileName() {
        return file_name;
    }
        
    /**
     * @param args the command line arguments
     */   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayCSVDataAsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayCSVDataAsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayCSVDataAsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayCSVDataAsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            DisplayCSVDataAsTable tableDisplay = new DisplayCSVDataAsTable();
            tableDisplay.setVisible(true);
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable csv_table;
    private javax.swing.JButton hide_btn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
