/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teslapowerwallvalidate;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author markvaleri
 */
public class StatusPage extends javax.swing.JFrame {

    double dNumPowerwalls = 0.0;;
    double dUsableCapacityPerBatKWH = 0.0;
    double dTotalUsableCapacityKWH = 0.0;
    double dPercentReservedCapacity = 0.0;;
    double dReservedCapacityKWH = 0.0;;
    double dSelfConsumeCapacityKWH = 0.0;;
    double dPerentRTefficiency = 0.0;
    
    File file1;     //object that holds path bane allows access to inducudule components
    File file2;
    
    DisplayCSVDataAsTable displayFile1;
    DisplayCSVDataAsTable displayFile2;
        
    /**
     * Creates new form StatusPage
     */
    public StatusPage() {
        initComponents();
        initUserDefinedComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        File1StatPanel = new javax.swing.JPanel();
        titleDateFile1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jInputFile1 = new javax.swing.JTextField();
        jBrowseFile1 = new javax.swing.JButton();
        jInputFile2 = new javax.swing.JTextField();
        jBrowseFile2 = new javax.swing.JButton();
        PWConfigPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selfConsumeCapacityKWH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        reservedCapacityKWH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        percentReservedCapacity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        totalUsableCapacity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        usableCapacity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numPowerwalls = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        percentReserveSlider = new javax.swing.JSlider();
        numBatSlider = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();
        RTefficiencySlider = new javax.swing.JSlider();
        percentRTefficiency = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        displayFile1Button = new javax.swing.JButton();
        File1BatAnalysisPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jEditMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        File1StatPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleDateFile1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleDateFile1.setText("File Not Opened");
        titleDateFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleDateFile1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Home");

        jTextField1.setText("jTextField1");

        jLabel21.setText("kHW");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Import");

        jLabel16.setText("Grid");

        jTextField3.setText("jTextField1");

        jLabel22.setText("kHW");

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Export");

        jTextField5.setText("jTextField1");

        jLabel28.setText("kHW");

        jLabel18.setText("Battery");

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Discahrge");

        jTextField2.setText("jTextField1");

        jLabel23.setText("kHW");

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Comspumption");

        jLabel24.setText("Solar");

        jTextField4.setText("jTextField1");

        jLabel25.setText("kHW");

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Export");

        jTextField6.setText("jTextField1");

        jLabel30.setText("kHW");

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Charge");

        jTextField7.setText("jTextField1");

        jLabel32.setText("kHW");

        javax.swing.GroupLayout File1StatPanelLayout = new javax.swing.GroupLayout(File1StatPanel);
        File1StatPanel.setLayout(File1StatPanelLayout);
        File1StatPanelLayout.setHorizontalGroup(
            File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File1StatPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(File1StatPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel27)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(File1StatPanelLayout.createSequentialGroup()
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(File1StatPanelLayout.createSequentialGroup()
                                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel25))
                                            .addComponent(jLabel22))
                                        .addGap(8, 8, 8)
                                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(File1StatPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(jLabel31)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(titleDateFile1)
        );
        File1StatPanelLayout.setVerticalGroup(
            File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File1StatPanelLayout.createSequentialGroup()
                .addComponent(titleDateFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(File1StatPanelLayout.createSequentialGroup()
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel22))
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(File1StatPanelLayout.createSequentialGroup()
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, File1StatPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addGroup(File1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(File1StatPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel32)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel30)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jBrowseFile1.setBackground(new java.awt.Color(102, 255, 102));
        jBrowseFile1.setText("Browse");
        jBrowseFile1.setToolTipText("Tes;a App Day Export");
        jBrowseFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseFile1ActionPerformed(evt);
            }
        });

        jBrowseFile2.setBackground(new java.awt.Color(102, 255, 102));
        jBrowseFile2.setText("Browse");
        jBrowseFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseFile2ActionPerformed(evt);
            }
        });

        PWConfigPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("# of Powerwalls:");

        jLabel2.setText("Usable Capcity:");

        jLabel3.setText("Total Usable Capacit:");

        jLabel4.setText("% Reserve Capacity:");

        jLabel5.setText("Reserve Capacity:");

        jLabel6.setText("Self Comsuption Capacity:");

        selfConsumeCapacityKWH.setEditable(false);
        selfConsumeCapacityKWH.setBackground(new java.awt.Color(153, 153, 255));
        selfConsumeCapacityKWH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        selfConsumeCapacityKWH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("kWh");

        reservedCapacityKWH.setEditable(false);
        reservedCapacityKWH.setBackground(new java.awt.Color(153, 153, 255));
        reservedCapacityKWH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        reservedCapacityKWH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("kWh");

        percentReservedCapacity.setBackground(new java.awt.Color(51, 255, 51));
        percentReservedCapacity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        percentReservedCapacity.setText("50");
        percentReservedCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        percentReservedCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentReservedCapacityActionPerformed(evt);
            }
        });

        jLabel12.setText("%");

        totalUsableCapacity.setEditable(false);
        totalUsableCapacity.setBackground(new java.awt.Color(153, 153, 255));
        totalUsableCapacity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalUsableCapacity.setText("13.5");
        totalUsableCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("kWh");

        usableCapacity.setBackground(new java.awt.Color(51, 255, 51));
        usableCapacity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        usableCapacity.setText("13.5");
        usableCapacity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usableCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usableCapacityActionPerformed(evt);
            }
        });

        jLabel8.setText("kWh");

        numPowerwalls.setBackground(new java.awt.Color(51, 255, 51));
        numPowerwalls.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPowerwalls.setText("3");
        numPowerwalls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numPowerwalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPowerwallsActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("-");

        percentReserveSlider.setMinimum(10);
        percentReserveSlider.setMinorTickSpacing(10);
        percentReserveSlider.setPaintTicks(true);
        percentReserveSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                percentReserveSliderStateChanged(evt);
            }
        });

        numBatSlider.setMaximum(10);
        numBatSlider.setMinimum(1);
        numBatSlider.setMinorTickSpacing(1);
        numBatSlider.setPaintTicks(true);
        numBatSlider.setValue(3);
        numBatSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numBatSliderStateChanged(evt);
            }
        });

        jLabel13.setText("Round Trip Efficiency:");

        RTefficiencySlider.setMinimum(10);
        RTefficiencySlider.setMinorTickSpacing(10);
        RTefficiencySlider.setPaintTicks(true);
        RTefficiencySlider.setValue(90);
        RTefficiencySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RTefficiencySliderStateChanged(evt);
            }
        });

        percentRTefficiency.setBackground(new java.awt.Color(51, 255, 51));
        percentRTefficiency.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        percentRTefficiency.setText("90");
        percentRTefficiency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        percentRTefficiency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentRTefficiencyActionPerformed(evt);
            }
        });

        jLabel14.setText("%");

        javax.swing.GroupLayout PWConfigPanelLayout = new javax.swing.GroupLayout(PWConfigPanel);
        PWConfigPanel.setLayout(PWConfigPanelLayout);
        PWConfigPanelLayout.setHorizontalGroup(
            PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PWConfigPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PWConfigPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13))
                        .addGap(35, 35, 35)
                        .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selfConsumeCapacityKWH, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservedCapacityKWH, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalUsableCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usableCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PWConfigPanelLayout.createSequentialGroup()
                                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(RTefficiencySlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(percentReserveSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(percentReservedCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(percentRTefficiency, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(PWConfigPanelLayout.createSequentialGroup()
                        .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numBatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numPowerwalls, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(30, 30, 30)
                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
        PWConfigPanelLayout.setVerticalGroup(
            PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PWConfigPanelLayout.createSequentialGroup()
                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PWConfigPanelLayout.createSequentialGroup()
                        .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PWConfigPanelLayout.createSequentialGroup()
                                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PWConfigPanelLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PWConfigPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(PWConfigPanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(usableCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(numBatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(numPowerwalls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)))))
                                .addGap(18, 18, 18)
                                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(totalUsableCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PWConfigPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(percentReserveSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(percentReservedCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PWConfigPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservedCapacityKWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selfConsumeCapacityKWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(PWConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RTefficiencySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentRTefficiency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        displayFile1Button.setText("Display File1");
        displayFile1Button.setToolTipText("");
        displayFile1Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayFile1ButtonKeyPressed(evt);
            }
        });

        File1BatAnalysisPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Battery Analysis");

        javax.swing.GroupLayout File1BatAnalysisPanelLayout = new javax.swing.GroupLayout(File1BatAnalysisPanel);
        File1BatAnalysisPanel.setLayout(File1BatAnalysisPanelLayout);
        File1BatAnalysisPanelLayout.setHorizontalGroup(
            File1BatAnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File1BatAnalysisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        File1BatAnalysisPanelLayout.setVerticalGroup(
            File1BatAnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(File1BatAnalysisPanelLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGroup(File1BatAnalysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(File1BatAnalysisPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel33))
                    .addGroup(File1BatAnalysisPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jFileMenu.setText("File");
        jMenuBar1.add(jFileMenu);

        jEditMenu.setText("Edit");
        jMenuBar1.add(jEditMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(PWConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayFile1Button)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(File1BatAnalysisPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jInputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jBrowseFile1))
                                .addComponent(File1StatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jInputFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jBrowseFile2)))))
                .addContainerGap(623, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PWConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInputFile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseFile2)
                    .addComponent(jBrowseFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(File1StatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(displayFile1Button)
                .addGap(18, 18, 18)
                .addComponent(File1BatAnalysisPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initUserDefinedComponents() {
         conputeBatStat();
         displayFile1 = new DisplayCSVDataAsTable();
         displayFile1.setTitle("File1");
         displayFile1.setVisible(false);
    }
    
    public void conputeBatStat() {
        dNumPowerwalls = Double.parseDouble(numPowerwalls.getText());
        numBatSlider.setValue((int) Math.floor(dNumPowerwalls));
        dUsableCapacityPerBatKWH = Double.parseDouble(usableCapacity.getText());
        dTotalUsableCapacityKWH = dNumPowerwalls * dUsableCapacityPerBatKWH;
        totalUsableCapacity.setText(String.valueOf(dTotalUsableCapacityKWH));
        dPercentReservedCapacity = Double.parseDouble(percentReservedCapacity.getText());
        percentReserveSlider.setValue((int) Math.floor(dPercentReservedCapacity));
        dReservedCapacityKWH = dTotalUsableCapacityKWH * dPercentReservedCapacity / 100.0;
        reservedCapacityKWH.setText(String.valueOf(dReservedCapacityKWH));
        dSelfConsumeCapacityKWH = dTotalUsableCapacityKWH - dReservedCapacityKWH;
        selfConsumeCapacityKWH.setText(String.valueOf(dSelfConsumeCapacityKWH));
        dPerentRTefficiency = Double.parseDouble(percentRTefficiency.getText()); 
        RTefficiencySlider.setValue((int) Math.floor(dPerentRTefficiency));
    }
            

    private void jBrowseFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseFile1ActionPerformed
        JFileChooser fileChooser1 = new JFileChooser();
        FileNameExtensionFilter filter1 = new FileNameExtensionFilter(
                "Comma Seperated Value", "csv");
        
        fileChooser1.setFileFilter(filter1);int option = fileChooser1.showOpenDialog(null );
        if (option == JFileChooser.APPROVE_OPTION){
            file1 = fileChooser1.getSelectedFile();
               jInputFile1.setText(file1.getName());
            } else {
               jInputFile1.setText("Open command canceled");
            }
       // TODO add your handling code here:
    }//GEN-LAST:event_jBrowseFile1ActionPerformed

    private void jBrowseFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseFile2ActionPerformed
        JFileChooser fileChooser2 = new JFileChooser();
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter(
                "Comma Seperated Value", "csv");
        
        fileChooser2.setFileFilter(filter2);int option = fileChooser2.showOpenDialog(null );
        if (option == JFileChooser.APPROVE_OPTION){
            file2 = fileChooser2.getSelectedFile();
               jInputFile2.setText(file2.getName());
            } else {
               jInputFile2.setText("Open command canceled");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrowseFile2ActionPerformed

    private void titleDateFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleDateFile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleDateFile1ActionPerformed

    private void numPowerwallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPowerwallsActionPerformed
        conputeBatStat();
        // TODO add your handling code here:
    }//GEN-LAST:event_numPowerwallsActionPerformed

    private void usableCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usableCapacityActionPerformed
        conputeBatStat();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_usableCapacityActionPerformed

    private void percentReservedCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentReservedCapacityActionPerformed
        conputeBatStat();
        // TODO add your handling code here:
    }//GEN-LAST:event_percentReservedCapacityActionPerformed

    private void percentReserveSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_percentReserveSliderStateChanged
        int i = percentReserveSlider.getValue();
        dPercentReservedCapacity = (double) i;
        percentReservedCapacity.setText(String.valueOf(i));
        conputeBatStat();
        // TODO add your handling code here:
    }//GEN-LAST:event_percentReserveSliderStateChanged

    private void numBatSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numBatSliderStateChanged
        int i = numBatSlider.getValue();
        dNumPowerwalls = (double) i;
        numPowerwalls.setText(String.valueOf(i));
        conputeBatStat();
       // TODO add your handling code here:
    }//GEN-LAST:event_numBatSliderStateChanged

    private void percentRTefficiencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentRTefficiencyActionPerformed
        conputeBatStat();
        // TODO add your handling code here:
    }//GEN-LAST:event_percentRTefficiencyActionPerformed

    private void RTefficiencySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RTefficiencySliderStateChanged
        int i = RTefficiencySlider.getValue();
        dPerentRTefficiency = (double) i;
        percentRTefficiency.setText(String.valueOf(i));
        conputeBatStat();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_RTefficiencySliderStateChanged

    private void displayFile1ButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayFile1ButtonKeyPressed
         displayFile1.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_displayFile1ButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StatusPage().setVisible(true);
        });
    }
    
    // End of User Generated Variables declaration - 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel File1BatAnalysisPanel;
    private javax.swing.JPanel File1StatPanel;
    private javax.swing.JPanel PWConfigPanel;
    private javax.swing.JSlider RTefficiencySlider;
    private javax.swing.JButton displayFile1Button;
    private javax.swing.JButton jBrowseFile1;
    private javax.swing.JButton jBrowseFile2;
    private javax.swing.JMenu jEditMenu;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JTextField jInputFile1;
    private javax.swing.JTextField jInputFile2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JSlider numBatSlider;
    private javax.swing.JTextField numPowerwalls;
    private javax.swing.JTextField percentRTefficiency;
    private javax.swing.JSlider percentReserveSlider;
    private javax.swing.JTextField percentReservedCapacity;
    private javax.swing.JTextField reservedCapacityKWH;
    private javax.swing.JTextField selfConsumeCapacityKWH;
    private javax.swing.JTextField titleDateFile1;
    private javax.swing.JTextField totalUsableCapacity;
    private javax.swing.JTextField usableCapacity;
    // End of variables declaration//GEN-END:variables
}
